//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
        }

        public int UserID { get; set; }

        [Required(ErrorMessage = "Khong duoc de trong")]
        [Display(Name = "Ten dang nhap")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Khong duoc de trong")]
        [Display(Name = "Mat khau")]
        [DataType(DataType.Password)]
        public string Userpassword { get; set; }

        [Required(ErrorMessage = "Khong duoc de trong")]
        [Display(Name = "Nhap lai mat khau")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("Userpassword", ErrorMessage = "Nhap lai mat khau khong chinh xac")]
        public string ReUserpassword { get; set; }

        [Required(ErrorMessage = "Khong duoc de trong")]
        [EmailAddress(ErrorMessage = "Email khong hop le")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Khong duoc de trong")]
        [Display(Name = "Role")]
        public string UserRole { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
